/*
Name: Daniel Araujo
Date: 03 Aug 18
Title: Math Methods
Purpose: to use a GUI to demonstrate mutliple math methods along with using custom methods
*/

package math.methods;

public class MathMethodsGUI extends javax.swing.JFrame {

    /**
     * Creates new form MathMethodsGUI
     */
    public MathMethodsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInsertValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        lblOption = new javax.swing.JLabel();
        btnRound = new javax.swing.JButton();
        btnAbsoluteValue = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnNaturalLog = new javax.swing.JButton();
        lblAnswer = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 102));
        lblTitle.setText("Math Methods");

        lblInsertValue.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        lblInsertValue.setText("Please insert a value:");

        txtValue.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txtValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblOption.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        lblOption.setText("Choose an option below:");

        btnRound.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        btnRound.setText("Round");
        btnRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoundActionPerformed(evt);
            }
        });

        btnAbsoluteValue.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        btnAbsoluteValue.setText("Absolute Value");
        btnAbsoluteValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsoluteValueActionPerformed(evt);
            }
        });

        btnSquare.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        btnSquare.setText("Square");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnSquareRoot.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        btnSquareRoot.setText("Square Root");
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });

        btnNaturalLog.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        btnNaturalLog.setText("Natural Log");
        btnNaturalLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaturalLogActionPerformed(evt);
            }
        });

        lblAnswer.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        lblAnswer.setText("Answer:");

        txtAnswer.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOption)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInsertValue)
                                .addGap(36, 36, 36)
                                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAbsoluteValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNaturalLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtAnswer)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(lblAnswer)
                                .addContainerGap(84, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertValue)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbsoluteValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSquare)
                    .addComponent(lblAnswer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSquareRoot)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNaturalLog)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoundActionPerformed
        double dblAnswer = Math.round(value()); // //declares the dblAnswer variable and stores the user's input (attained by calling the value method) and applies the round math method
        
        answer(dblAnswer); //calls on the answer() method - passes double variable dblAnswer as the parameter
    }//GEN-LAST:event_btnRoundActionPerformed

    private void btnAbsoluteValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsoluteValueActionPerformed
        double dblAnswer = Math.abs(value()); //declares the dblAnswer variable and stores the user's input (attained by calling the value method) and applies the absolute value math method
        
        answer(dblAnswer); //calls on the answer() method - passes double variable dblAnswer as the parameter
    }//GEN-LAST:event_btnAbsoluteValueActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        double dblAnswer = Math.pow(value(),2); //declares the dblAnswer variable and stores the user's input (attained by calling the value method) and applies the power math method (2 is used to square the value)
        
        answer(dblAnswer); //calls on the answer() method - passes double variable dblAnswer as the parameter
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        double dblAnswer = Math.sqrt(value()); //declares the dblAnswer variable and stores the user's input (attained by calling the value method) and applies the square root math method
        
        answer(dblAnswer); //calls on the answer() method - passes double variable dblAnswer as the parameter
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnNaturalLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaturalLogActionPerformed
        double dblAnswer = Math.log(value()); //declares the dblAnswer variable and stores the user's input (attained by calling the value method) and applies the natural log math method
        
        answer(dblAnswer); //calls on the answer() method - passes double variable dblAnswer as the parameter
    }//GEN-LAST:event_btnNaturalLogActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //closes the application when the exit button is pressed
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * value()
     * takes the the text in the txtValue box and converts it to a double variable
     * @return double value - is the value the user inputted
     */
    public double value(){
        return Double.parseDouble(txtValue.getText());
    }
    /**
     * answer()
     * one double value must be placed as a parameter when calling the method
     * the txtAnswer text box will output the dblAnswer variable after converting it to a string value
     * @param dblAnswer double value - is the answer after the math method has been applied
     */
    public void answer(double dblAnswer) {
        txtAnswer.setText(Double.toString(dblAnswer)); //outputs the answer in the txtAnswer box
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathMethodsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathMethodsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathMethodsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathMethodsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathMethodsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsoluteValue;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNaturalLog;
    private javax.swing.JButton btnRound;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblInsertValue;
    private javax.swing.JLabel lblOption;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
